
notifications:
  commits:              commits@infra.apache.org
  pullrequests:         commits@infra.apache.org
  issues:               private@infra.apache.org
  jobs:                 private@infra.apache.org
  jira_options:         comment link label
