passing_commit = {
    "project": "superset",
    "hash": "951d7d66",
    "sha": "951d7d66ac00d32032317f4d7085391db6325d11",
}
passing_wdata = {"path": ".github/workflows/license-check.yml"}
passing_workflow = {
    "name": "License Template Check",
    True: {
        "pull_request": {
            "types": ["synchronize", "opened", "reopened", "ready_for_review"]
        }
    },
    "concurrency": {
        "group": "${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}",
        "cancel-in-progress": True,
    },
    "jobs": {
        "license_check": {
            "name": "License Check",
            "runs-on": "ubuntu-20.04",
            "steps": [
                {
                    "name": "Checkout ${{ github.ref }} ( ${{ github.sha }} )",
                    "uses": "actions/checkout@v4",
                    "with": {"persist-credentials": False, "submodules": "recursive"},
                },
                {
                    "name": "Setup Java",
                    "uses": "actions/setup-java@v4",
                    "with": {"distribution": "temurin", "java-version": "11"},
                },
                {"name": "Run license check", "run": "./scripts/check_license.sh"},
            ],
        }
    },
}
failing_check_prt = {
    "name": "Dev PR",
    True: {"pull_request_target": {"types": ["opened", "edited", "synchronize"]}},
    "concurrency": {
        "group": "${{ github.workflow }}-${{ github.repository }}-${{ github.event.number }}",
        "cancel-in-progress": True,
    },
    "permissions": {"contents": "read", "pull-requests": "write", "issues": "write"},
    "jobs": {
        "process": {
            "name": "Process",
            "runs-on": "ubuntu-latest",
            "steps": [
                {
                    "uses": "actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac",
                    "with": {
                        "repository": "apache/arrow",
                        "ref": "main",
                        "persist-credentials": False,
                    },
                },
                {
                    "name": "Comment JIRA link",
                    "if": "(github.event.action == 'opened' ||\n github.event.action == 'edited')\n",
                    "uses": "actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea",
                    "with": {
                        "github-token": "${{ secrets.GITHUB_TOKEN }}",
                        "script": "const script = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/dev_pr/link.js`);\nscript({github, context});\n",
                    },
                },
                {
                    "name": "Check title",
                    "if": "(github.event.action == 'opened' ||\n github.event.action == 'edited')\n",
                    "uses": "actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea",
                    "with": {
                        "github-token": "${{ secrets.GITHUB_TOKEN }}",
                        "script": "const script = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/dev_pr/title_check.js`);\nscript({github, context});\n",
                    },
                },
                {
                    "name": "Check Issue",
                    "if": "(github.event.action == 'opened' ||\n github.event.action == 'edited')\n",
                    "uses": "actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea",
                    "with": {
                        "debug": True,
                        "github-token": "${{ secrets.GITHUB_TOKEN }}",
                        "script": "const script = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/dev_pr/issue_check.js`);\nscript({github, context});\n",
                    },
                },
                {
                    "name": "Assign GitHub labels",
                    "if": "(github.event.action == 'opened' ||\n github.event.action == 'synchronize')\n",
                    "uses": "actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594",
                    "with": {
                        "repo-token": "${{ secrets.GITHUB_TOKEN }}",
                        "configuration-path": ".github/workflows/dev_pr/labeler.yml",
                        "sync-labels": True,
                    },
                },
            ],
        }
    },
}
failed_concurrency = {
    "name": "ci",
    "True": {"pull_request": None, "push": {"branches": ["master"]}},
    "jobs": {
        "build": {
            "strategy": {
                "matrix": {
                    "java": [8, 11],
                    "os": ["ubuntu-latest", "macos-latest", "windows-latest"],
                    "include": [
                        {"java": 12, "os": "ubuntu-latest"},
                        {"java": 13, "os": "ubuntu-latest"},
                        {"java": 14, "os": "ubuntu-latest"},
                        {"java": 15, "os": "ubuntu-latest"},
                        {"java": 16, "os": "ubuntu-latest"},
                        {"java": 17, "os": "ubuntu-latest"},
                        {"java": 18, "os": "ubuntu-latest"},
                        {"java": 19, "os": "ubuntu-latest"},
                        {"java": 20, "os": "ubuntu-latest"},
                        {"java": 21, "os": "ubuntu-latest"},
                    ],
                }
            },
            "runs-on": "${{ matrix.os }}",
            "if": "(github.repository == 'apache/shenyu')",
            "steps": [
                {
                    "name": "Support longpaths",
                    "if": "${{ matrix.os == 'windows-latest'}}",
                    "run": "git config --system core.longpaths True",
                },
                {"uses": "actions/checkout@v3", "with": {"submodules": True}},
                {
                    "uses": "dorny/paths-filter@v2",
                    "id": "filter",
                    "with": {"filters": ".github/filters.yml", "list-files": "json"},
                },
                {
                    "name": "Restore ShenYu Maven Repos",
                    "if": "steps.filter.outputs.changed == 'True'",
                    "id": "restore-maven-cache",
                    "uses": "actions/cache/restore@v3",
                    "with": {
                        "path": "~/.m2/repository",
                        "key": "${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}",
                        "restore-keys": "${{ runner.os }}-maven-\n",
                    },
                },
                {
                    "uses": "actions/setup-java@v1",
                    "if": "steps.filter.outputs.changed == 'True'",
                    "with": {"java-version": "${{ matrix.java }}"},
                },
                {
                    "name": "Build with Maven",
                    "if": "steps.filter.outputs.changed == 'True'",
                    "run": "./mvnw -B clean test -Prelease",
                },
                {
                    "uses": "codecov/codecov-action@v1",
                    "if": "steps.filter.outputs.changed == 'True'",
                },
                {
                    "name": "Save ShenYu Maven Repos",
                    "if": "steps.filter.outputs.changed == 'True' && steps.restore-maven-cache.outputs.cache-hit != 'True'",
                    "uses": "actions/cache/save@v3",
                    "with": {
                        "path": "~/.m2/repository",
                        "key": "${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}",
                    },
                },
            ],
        },
        "check-license-header": {
            "name": "check-license-header",
            "runs-on": "ubuntu-latest",
            "timeout-minutes": 10,
            "steps": [
                {"uses": "actions/checkout@v3", "with": {"submodules": True}},
                {
                    "name": "Check License Header",
                    "uses": "apache/skywalking-eyes@9bd5feb86b5817aa6072b008f9866a2c3bbc8587",
                    "env": {"GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"},
                },
            ],
        },
        "requirement": {
            "name": "build",
            "if": "always()",
            "needs": ["build"],
            "runs-on": "ubuntu-latest",
            "steps": [
                {
                    "name": "checking job status",
                    "run": '[[ "${{ needs.build.result }}" == "success" ]] || exit -1\n',
                }
            ],
        },
    },
}
passing_list_flows = {
    "total_count": 57,
    "workflows": [
        {
            "id": 91145317,
            "node_id": "W_kwDOAlosUs4FbsRl",
            "name": "Bump Python Package",
            "path": ".github/workflows/bump-python-package.yml",
            "state": "active",
            "created_at": "2024-03-25T21:04:53.000-04:00",
            "updated_at": "2024-03-25T21:19:48.000-04:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/91145317",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/bump-python-package.yml",
            "badge_url": "https://github.com/apache/superset/workflows/Bump%20Python%20Package/badge.svg",
        },
        {
            "id": 4755967,
            "node_id": "MDg6V29ya2Zsb3c0NzU1OTY3",
            "name": "Cancel Duplicates",
            "path": ".github/workflows/cancel_duplicates.yml",
            "state": "active",
            "created_at": "2021-01-07T03:47:08.000-05:00",
            "updated_at": "2021-01-07T03:47:08.000-05:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/4755967",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/cancel_duplicates.yml",
            "badge_url": "https://github.com/apache/superset/workflows/Cancel%20Duplicates/badge.svg",
        },
        {
            "id": 83736198,
            "node_id": "W_kwDOAlosUs4E_baG",
            "name": ".github/workflows/check-envvar.yml",
            "path": ".github/workflows/check-envvar.yml",
            "state": "active",
            "created_at": "2024-01-25T16:44:03.000-05:00",
            "updated_at": "2024-01-25T16:44:03.000-05:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/83736198",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/check-envvar.yml",
            "badge_url": "https://github.com/apache/superset/workflows/.github/workflows/check-envvar.yml/badge.svg",
        },
        {
            "id": 6585470,
            "node_id": "MDg6V29ya2Zsb3c2NTg1NDcw",
            "name": "Check DB migration conflict",
            "path": ".github/workflows/check_db_migration_confict.yml",
            "state": "active",
            "created_at": "2021-03-10T19:03:00.000-05:00",
            "updated_at": "2024-03-04T17:57:41.000-05:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/6585470",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/check_db_migration_confict.yml",
            "badge_url": "https://github.com/apache/superset/workflows/Check%20DB%20migration%20conflict/badge.svg",
        },
        {
            "id": 33382254,
            "node_id": "W_kwDOAlosUs4B_V9u",
            "name": ".github/workflows/chromatic-pr.yml",
            "path": ".github/workflows/chromatic-pr.yml",
            "state": "active",
            "created_at": "2022-08-26T17:56:27.000-04:00",
            "updated_at": "2022-09-22T17:45:46.000-04:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/33382254",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/chromatic-pr.yml",
            "badge_url": "https://github.com/apache/superset/workflows/.github/workflows/chromatic-pr.yml/badge.svg",
        },
        {
            "id": 35290406,
            "node_id": "W_kwDOAlosUs4CGn0m",
            "name": "CodeQL",
            "path": ".github/workflows/codeql-analysis.yml",
            "state": "active",
            "created_at": "2022-09-19T16:22:03.000-04:00",
            "updated_at": "2023-05-05T14:40:01.000-04:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/35290406",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/codeql-analysis.yml",
            "badge_url": "https://github.com/apache/superset/workflows/CodeQL/badge.svg",
        },
        {
            "id": 56394524,
            "node_id": "W_kwDOAlosUs4DXIMc",
            "name": "Dependency Review",
            "path": ".github/workflows/dependency-review.yml",
            "state": "active",
            "created_at": "2023-05-05T15:11:49.000-04:00",
            "updated_at": "2023-05-10T10:08:35.000-04:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/56394524",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/dependency-review.yml",
            "badge_url": "https://github.com/apache/superset/workflows/Dependency%20Review/badge.svg",
        },
        {
            "id": 83616740,
            "node_id": "W_kwDOAlosUs4E--Pk",
            "name": ".github/workflows/docker-builds.yml",
            "path": ".github/workflows/docker-builds.yml",
            "state": "active",
            "created_at": "2024-01-24T19:39:15.000-05:00",
            "updated_at": "2024-01-24T19:39:15.000-05:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/83616740",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/docker-builds.yml",
            "badge_url": "https://github.com/apache/superset/workflows/.github/workflows/docker-builds.yml/badge.svg",
        },
        {
            "id": 4796916,
            "node_id": "MDg6V29ya2Zsb3c0Nzk2OTE2",
            "name": "Docker",
            "path": ".github/workflows/docker-release.yml",
            "state": "active",
            "created_at": "2021-01-08T18:00:03.000-05:00",
            "updated_at": "2024-04-02T09:31:18.000-04:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/4796916",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/docker-release.yml",
            "badge_url": "https://github.com/apache/superset/workflows/Docker/badge.svg",
        },
        {
            "id": 3465823,
            "node_id": "MDg6V29ya2Zsb3czNDY1ODIz",
            "name": "Build & publish docker images",
            "path": ".github/workflows/docker.yml",
            "state": "active",
            "created_at": "2020-11-09T00:09:27.000-05:00",
            "updated_at": "2024-04-01T15:21:22.000-04:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/3465823",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/docker.yml",
            "badge_url": "https://github.com/apache/superset/workflows/Build%20&%20publish%20docker%20images/badge.svg",
        },
        {
            "id": 19161392,
            "node_id": "W_kwDOAlosUs4BJGEw",
            "name": "Embedded SDK Release",
            "path": ".github/workflows/embedded-sdk-release.yml",
            "state": "active",
            "created_at": "2022-02-02T16:39:57.000-05:00",
            "updated_at": "2024-03-04T16:27:03.000-05:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/19161392",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/embedded-sdk-release.yml",
            "badge_url": "https://github.com/apache/superset/workflows/Embedded%20SDK%20Release/badge.svg",
        },
        {
            "id": 19163777,
            "node_id": "W_kwDOAlosUs4BJGqB",
            "name": "Embedded SDK PR Checks",
            "path": ".github/workflows/embedded-sdk-test.yml",
            "state": "active",
            "created_at": "2022-02-02T17:31:32.000-05:00",
            "updated_at": "2022-02-03T17:01:54.000-05:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/19163777",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/embedded-sdk-test.yml",
            "badge_url": "https://github.com/apache/superset/workflows/Embedded%20SDK%20PR%20Checks/badge.svg",
        },
        {
            "id": 6543333,
            "node_id": "MDg6V29ya2Zsb3c2NTQzMzMz",
            "name": "Cleanup ephemeral envs (PR close)",
            "path": ".github/workflows/ephemeral-env-pr-close.yml",
            "state": "active",
            "created_at": "2021-03-09T13:19:46.000-05:00",
            "updated_at": "2021-03-09T13:19:46.000-05:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/6543333",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/ephemeral-env-pr-close.yml",
            "badge_url": "https://github.com/apache/superset/workflows/Cleanup%20ephemeral%20envs%20(PR%20close)/badge.svg",
        },
        {
            "id": 6121851,
            "node_id": "MDg6V29ya2Zsb3c2MTIxODUx",
            "name": "Ephemeral env workflow",
            "path": ".github/workflows/ephemeral-env.yml",
            "state": "active",
            "created_at": "2021-02-24T13:50:57.000-05:00",
            "updated_at": "2021-02-24T13:50:57.000-05:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/6121851",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/ephemeral-env.yml",
            "badge_url": "https://github.com/apache/superset/workflows/Ephemeral%20env%20workflow/badge.svg",
        },
        {
            "id": 84150969,
            "node_id": "W_kwDOAlosUs4FBAq5",
            "name": "Generate FOSSA report",
            "path": ".github/workflows/generate-FOSSA-report.yml",
            "state": "active",
            "created_at": "2024-01-29T18:18:52.000-05:00",
            "updated_at": "2024-01-29T18:18:52.000-05:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/84150969",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/generate-FOSSA-report.yml",
            "badge_url": "https://github.com/apache/superset/workflows/Generate%20FOSSA%20report/badge.svg",
        },
        {
            "id": 34413817,
            "node_id": "W_kwDOAlosUs4CDRz5",
            "name": "Generate Technical Debt Metrics",
            "path": ".github/workflows/generate_tech_debt_metrics.yml",
            "state": "active",
            "created_at": "2022-09-09T00:16:02.000-04:00",
            "updated_at": "2022-09-14T11:16:07.000-04:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/34413817",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/generate_tech_debt_metrics.yml",
            "badge_url": "https://github.com/apache/superset/workflows/Generate%20Technical%20Debt%20Metrics/badge.svg",
        },
        {
            "id": 90341178,
            "node_id": "W_kwDOAlosUs4FYn86",
            "name": "supersetbot orglabel based on author",
            "path": ".github/workflows/issue_creation.yml",
            "state": "active",
            "created_at": "2024-03-19T20:35:31.000-04:00",
            "updated_at": "2024-03-20T12:31:03.000-04:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/90341178",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/issue_creation.yml",
            "badge_url": "https://github.com/apache/superset/workflows/supersetbot%20orglabel%20based%20on%20author/badge.svg",
        },
        {
            "id": 83020014,
            "node_id": "W_kwDOAlosUs4E8sju",
            "name": "Label Migration PR",
            "path": ".github/workflows/label-miration-pr.yml",
            "state": "active",
            "created_at": "2024-01-19T12:48:07.000-05:00",
            "updated_at": "2024-01-19T12:48:07.000-05:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/83020014",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/label-miration-pr.yml",
            "badge_url": "https://github.com/apache/superset/workflows/Label%20Migration%20PR/badge.svg",
        },
        {
            "id": 84165800,
            "node_id": "W_kwDOAlosUs4FBESo",
            "name": "Pull Request Labeler",
            "path": ".github/workflows/labeler.yml",
            "state": "active",
            "created_at": "2024-01-29T21:59:49.000-05:00",
            "updated_at": "2024-01-30T12:26:36.000-05:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/84165800",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/labeler.yml",
            "badge_url": "https://github.com/apache/superset/workflows/Pull%20Request%20Labeler/badge.svg",
        },
        {
            "id": 4334068,
            "node_id": "MDg6V29ya2Zsb3c0MzM0MDY4",
            "name": "Tags",
            "path": ".github/workflows/latest-release-tag.yml",
            "state": "active",
            "created_at": "2020-12-17T13:50:49.000-05:00",
            "updated_at": "2020-12-17T13:50:49.000-05:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/4334068",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/latest-release-tag.yml",
            "badge_url": "https://github.com/apache/superset/workflows/Tags/badge.svg",
        },
        {
            "id": 1024927,
            "node_id": "MDg6V29ya2Zsb3cxMDI0OTI3",
            "name": "License Template Check",
            "path": ".github/workflows/license-check.yml",
            "state": "active",
            "created_at": "2020-04-14T16:38:23.000-04:00",
            "updated_at": "2024-04-02T09:45:58.000-04:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/1024927",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/license-check.yml",
            "badge_url": "https://github.com/apache/superset/workflows/License%20Template%20Check/badge.svg",
        },
        {
            "id": 4722039,
            "node_id": "MDg6V29ya2Zsb3c0NzIyMDM5",
            "name": "Miscellaneous",
            "path": ".github/workflows/misc.yml",
            "state": "active",
            "created_at": "2021-01-05T19:06:11.000-05:00",
            "updated_at": "2022-07-05T06:09:05.000-04:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/4722039",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/misc.yml",
            "badge_url": "https://github.com/apache/superset/workflows/Miscellaneous/badge.svg",
        },
        {
            "id": 84157150,
            "node_id": "W_kwDOAlosUs4FBCLe",
            "name": "Hold Label Check",
            "path": ".github/workflows/no-hold-label.yml",
            "state": "active",
            "created_at": "2024-01-29T19:55:41.000-05:00",
            "updated_at": "2024-01-30T12:30:57.000-05:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/84157150",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/no-hold-label.yml",
            "badge_url": "https://github.com/apache/superset/workflows/Hold%20Label%20Check/badge.svg",
        },
        {
            "id": 83469164,
            "node_id": "W_kwDOAlosUs4E-aNs",
            "name": "no-op Checks",
            "path": ".github/workflows/no-op.yml",
            "state": "active",
            "created_at": "2024-01-23T18:21:02.000-05:00",
            "updated_at": "2024-04-02T08:26:52.000-04:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/83469164",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/no-op.yml",
            "badge_url": "https://github.com/apache/superset/workflows/no-op%20Checks/badge.svg",
        },
        {
            "id": 2668108,
            "node_id": "MDg6V29ya2Zsb3cyNjY4MTA4",
            "name": "PR Lint",
            "path": ".github/workflows/pr-lint.yml",
            "state": "active",
            "created_at": "2020-09-21T22:28:30.000-04:00",
            "updated_at": "2020-09-21T23:10:43.000-04:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/2668108",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/pr-lint.yml",
            "badge_url": "https://github.com/apache/superset/workflows/PR%20Lint/badge.svg",
        },
        {
            "id": 84437753,
            "node_id": "W_kwDOAlosUs4FCGr5",
            "name": "pre-commit checks",
            "path": ".github/workflows/pre-commit.yml",
            "state": "active",
            "created_at": "2024-01-31T17:59:13.000-05:00",
            "updated_at": "2024-03-04T16:27:03.000-05:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/84437753",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/pre-commit.yml",
            "badge_url": "https://github.com/apache/superset/workflows/pre-commit%20checks/badge.svg",
        },
        {
            "id": 2508631,
            "node_id": "MDg6V29ya2Zsb3cyNTA4NjMx",
            "name": "Prefer TypeScript",
            "path": ".github/workflows/prefer-typescript.yml",
            "state": "active",
            "created_at": "2020-09-09T15:47:40.000-04:00",
            "updated_at": "2024-03-04T16:54:37.000-05:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/2508631",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/prefer-typescript.yml",
            "badge_url": "https://github.com/apache/superset/workflows/Prefer%20TypeScript/badge.svg",
        },
        {
            "id": 16610251,
            "node_id": "W_kwDOAlosUs4A_XPL",
            "name": "release-workflow",
            "path": ".github/workflows/release.yml",
            "state": "active",
            "created_at": "2021-12-20T08:58:15.000-05:00",
            "updated_at": "2024-03-04T16:27:03.000-05:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/16610251",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/release.yml",
            "badge_url": "https://github.com/apache/superset/workflows/release-workflow/badge.svg",
        },
        {
            "id": 61115571,
            "node_id": "W_kwDOAlosUs4DpIyz",
            "name": ".github/workflows/security-ci.yml",
            "path": ".github/workflows/security-ci.yml",
            "state": "active",
            "created_at": "2023-06-23T00:57:18.000-04:00",
            "updated_at": "2023-06-23T00:57:18.000-04:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/61115571",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/security-ci.yml",
            "badge_url": "https://github.com/apache/superset/workflows/.github/workflows/security-ci.yml/badge.svg",
        },
        {
            "id": 25353440,
            "node_id": "W_kwDOAlosUs4Bgtzg",
            "name": "Applitools Cypress",
            "path": ".github/workflows/superset-applitool-cypress.yml",
            "state": "active",
            "created_at": "2022-05-03T07:29:16.000-04:00",
            "updated_at": "2024-03-21T21:25:52.000-04:00",
            "url": "https://api.github.com/repos/apache/superset/actions/workflows/25353440",
            "html_url": "https://github.com/apache/superset/blob/master/.github/workflows/superset-applitool-cypress.yml",
            "badge_url": "https://github.com/apache/superset/workflows/Applitools%20Cypress/badge.svg",
        },
    ],
}
